kind: pipeline
name: default

steps:
- name: test
  image: node
  environment:
    IPFS_URL:
      from_secret: ipfs_url
    IPFS_USERNAME:
      from_secret: ipfs_username
    IPFS_PASSWORD:
      from_secret: ipfs_password
  commands:
  - npm install
  - npm test